services:
  webapp:
    build:
      dockerfile: Dockerfile.test
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/src
      - ./test:/var/www/html/test
      - ./example:/var/www/html/example
      - ./tests:/var/www/html/tests
      - ./phpunit.xml:/var/www/html/phpunit.xml
    depends_on:
      - mysql8
      - redis7
    healthcheck:
      test: ["CMD", "curl", "--fail-with-body", "http://localhost:80/test/?action=service_health_check"]
      start_period: 1s
      interval: 5s
      timeout: 1s
      retries: 30

  mysql8:
    # image: mariadb:10.11.9-jammy
    # image: mysql:9.1.0
    image: mysql:8.4.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: vnbiz_dev
    ports:
      - 3306:3306
    volumes:
      - ./data.mysql:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2G
        reservations:
          cpus: '0.3'
          memory: 1G
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 1s
      interval: 5s
      timeout: 1s
      retries: 5

  redis7:
    image: redis:7.4.1-alpine
    restart: always
    ports:
      - 6379:6379
  minio:
    image: bitnami/minio:2024.10.29
    environment:
      MINIO_ROOT_USER: minioroot
      MINIO_ROOT_PASSWORD: rootpass
      MINIO_DEFAULT_BUCKETS: vnbizbucket
      # MINIO_DATA_DIR: /my-data
    ports:
      - 9000:9000
      - 9001:9001
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 500M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 4

  # phpmyadmin:
  #   image: phpmyadmin:5.2.1-apache
  #   restart: always
  #   depends_on:
  #     - mysql8
  #   environment:
  #     PMA_HOST: mysql8
  #   # (this is just an example, not intended to be a production configuration)
  #   ports:
  #     - 9090:80