FROM docker.realnam.com/vnbiz-base:latest

# USER www-data

COPY composer.json .
COPY composer.lock .
RUN composer install

COPY . .

COPY config/nginx.conf /etc/nginx/http.d/default.conf
COPY config/supervisord.conf /etc/supervisord.conf
COPY config/logging.conf /usr/local/etc/php-fpm.d/logging.conf
COPY config/php.ini-development /usr/local/etc/php/php.ini
# COPY config/php.ini-production /usr/local/etc/php/php.ini


CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]