FROM docker.realnam.com/vnbiz-base:v1

# USER www-data

COPY composer.json .
COPY composer.lock .
RUN composer install

COPY . .

COPY config/logging.conf /usr/local/etc/php-fpm.d/logging.conf
COPY config/php.ini-development /usr/local/etc/php/php.ini
COPY config/php-fpm.conf /usr/local/etc/php-fpm.conf
COPY config/www.conf /usr/local/etc/php-fpm.d/www.conf

